name: EngineRoom ðŸ‡¸ðŸ‡¬ 
title: EngineRoom ðŸ‡¸ðŸ‡¬ 
description: A social meetup for software creators
encoding: UTF-8
future: true
include:
  - speak.md
  - index.md
  - meetups.md
  - join-the-team.md
  - sponsor-us.md
  - _posts/*.md
google_analytics: UA-142320208-1
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
permalink: pretty
theme: minima
timezone: Asia/Singapore
